/** @type {import('./tripModel').Trip[]} */
export const MOCK_TRIPS = [
  {
    id: 't1',
    destination: 'Tokyo',
    country: 'Japan',
    startDate: '2024-03-15',
    endDate: '2024-03-25',
    coordinates: { latitude: 35.6762, longitude: 139.6503 },
    expenses: [
      { category: 'Food', amount: 620, currency: 'USD' },
      { category: 'Transport', amount: 340, currency: 'USD' },
      { category: 'Accommodation', amount: 1100, currency: 'USD' },
      { category: 'Activities', amount: 280, currency: 'USD' },
      { category: 'Shopping', amount: 450, currency: 'USD' },
    ],
    photos: 234,
    companions: ['Alice'],
  },
  {
    id: 't2',
    destination: 'Paris',
    country: 'France',
    startDate: '2024-06-01',
    endDate: '2024-06-08',
    coordinates: { latitude: 48.8566, longitude: 2.3522 },
    expenses: [
      { category: 'Food', amount: 480, currency: 'USD' },
      { category: 'Transport', amount: 210, currency: 'USD' },
      { category: 'Accommodation', amount: 980, currency: 'USD' },
      { category: 'Activities', amount: 350, currency: 'USD' },
      { category: 'Shopping', amount: 320, currency: 'USD' },
    ],
    photos: 189,
    companions: ['Bob', 'Alice'],
  },
  {
    id: 't3',
    destination: 'Bali',
    country: 'Indonesia',
    startDate: '2024-08-10',
    endDate: '2024-08-20',
    coordinates: { latitude: -8.3405, longitude: 115.092 },
    expenses: [
      { category: 'Food', amount: 310, currency: 'USD' },
      { category: 'Transport', amount: 150, currency: 'USD' },
      { category: 'Accommodation', amount: 720, currency: 'USD' },
      { category: 'Activities', amount: 420, currency: 'USD' },
      { category: 'Shopping', amount: 180, currency: 'USD' },
    ],
    photos: 312,
    companions: [],
  },
  {
    id: 't4',
    destination: 'New York',
    country: 'USA',
    startDate: '2024-11-20',
    endDate: '2024-11-27',
    coordinates: { latitude: 40.7128, longitude: -74.006 },
    expenses: [
      { category: 'Food', amount: 560, currency: 'USD' },
      { category: 'Transport', amount: 280, currency: 'USD' },
      { category: 'Accommodation', amount: 1400, currency: 'USD' },
      { category: 'Activities', amount: 390, currency: 'USD' },
      { category: 'Shopping', amount: 670, currency: 'USD' },
    ],
    photos: 156,
    companions: ['Charlie'],
  },
  {
    id: 't5',
    destination: 'Sydney',
    country: 'Australia',
    startDate: '2025-01-05',
    endDate: '2025-01-14',
    coordinates: { latitude: -33.8688, longitude: 151.2093 },
    expenses: [
      { category: 'Food', amount: 510, currency: 'USD' },
      { category: 'Transport', amount: 320, currency: 'USD' },
      { category: 'Accommodation', amount: 1200, currency: 'USD' },
      { category: 'Activities', amount: 450, currency: 'USD' },
      { category: 'Shopping', amount: 230, currency: 'USD' },
    ],
    photos: 278,
    companions: ['Alice', 'David'],
  },
  {
    id: 't6',
    destination: 'Tokyo',
    country: 'Japan',
    startDate: '2025-04-01',
    endDate: '2025-04-07',
    coordinates: { latitude: 35.6762, longitude: 139.6503 },
    expenses: [
      { category: 'Food', amount: 380, currency: 'USD' },
      { category: 'Transport', amount: 190, currency: 'USD' },
      { category: 'Accommodation', amount: 650, currency: 'USD' },
      { category: 'Activities', amount: 220, currency: 'USD' },
      { category: 'Shopping', amount: 300, currency: 'USD' },
    ],
    photos: 145,
    companions: [],
  },
  {
    id: 't7',
    destination: 'Barcelona',
    country: 'Spain',
    startDate: '2025-07-12',
    endDate: '2025-07-19',
    coordinates: { latitude: 41.3874, longitude: 2.1686 },
    expenses: [
      { category: 'Food', amount: 410, currency: 'USD' },
      { category: 'Transport', amount: 170, currency: 'USD' },
      { category: 'Accommodation', amount: 840, currency: 'USD' },
      { category: 'Activities', amount: 290, currency: 'USD' },
      { category: 'Shopping', amount: 260, currency: 'USD' },
    ],
    photos: 203,
    companions: ['Bob'],
  },
  {
    id: 't8',
    destination: 'Bangkok',
    country: 'Thailand',
    startDate: '2025-10-03',
    endDate: '2025-10-10',
    coordinates: { latitude: 13.7563, longitude: 100.5018 },
    expenses: [
      { category: 'Food', amount: 240, currency: 'USD' },
      { category: 'Transport', amount: 110, currency: 'USD' },
      { category: 'Accommodation', amount: 480, currency: 'USD' },
      { category: 'Activities', amount: 190, currency: 'USD' },
      { category: 'Shopping', amount: 150, currency: 'USD' },
    ],
    photos: 167,
    companions: ['Charlie', 'Eve'],
  },
];
